### PR TITLE
Consolidate resources into new site section

### PR DESCRIPTION
**Pull request by semioticrobotic**
This pull request suggests simplifying our primary site navigation by consolidating community resources in a new site section called (appropriately) "Resources." Also included in the new section are pre-existing resources that are rather difficult to locate.

### CODE REVIEW

**Comment by semioticrobotic** [comment]
Requesting @LauraHilliger input and review on this proposed change.

**Comment by LauraHilliger** [comment]
Heya - so from a UX perspective, we would want to _reduce_ the number of clicks a user needs to make to access the most important information. Might seem arbitrary but it's really about reducing a users need for cognitive capacity in finding what they need. 

So I guess I would ask what problem are you trying to solve with this change?

Perhaps it's just "Definition" that is an incorrect global nav descriptor? Because it could be "resources" or "models" and then we put the Def, Maturity model and the new OLD one more click away (but leave Books, Articles, Videos as top-level)?

**Comment by semioticrobotic** [comment]
> So I guess I would ask what problem are you trying to solve with this change?

Always the best question. Thank you.

Two things

- I was thinking ahead to the launch of the Open Leadership Definition and determining where it might live. At the moment, there's no landing page for "definitions and models," because we only have one: the Open Organization Definition (which contains a link to the Open Organization Maturity Model at the end). So I was trying to determine where we'd feature the Open Leadership Definition and figured, _Hey, maybe we should just have a landing page for all our resources._ But I see now this might not be the best decision.
- Additionally, I am trying to save screen real estate. Collapsing a browser window—or viewing the site on mobile—makes the menu do some wacky things because it's so wide. And when viewed in a mobile browser, the buttons cascade way down the screen and eat a lot of space. So I was thinking of ways to minimize buttons.
- One nice benefit of this change is that the page now surfaces the "roster" page, which is really obscured in the current configuration (accessible only if one knows the URL).

So there's my thinking, for what it's worth!

> Perhaps it's just "Definition" that is an incorrect global nav descriptor? Because it could be "resources" or "models" and then we put the Def, Maturity model and the new OLD one more click away (but leave Books, Articles, Videos as top-level)?

The issue with moving the top-level link to the Open Organization Definition is that _so many_ things already link to it at ``theopenorganization.org/definition``. If we remove that hyperlink, we break stuff. So I wanted to remain sensitive to that. But hey—maybe we just do it the name of Progress and tidy the trail of broken links as we find them (in articles and other places online). Something to discuss.

From a usability perspective, I'd prefer not to rely too heavily on dropdown menus because I always have trouble with sites that implement these when I'm using a mobile device. "Hovering" isn't really a thing with a touch interface.

**Comment by LauraHilliger** [comment]
> Additionally, I am trying to save screen real estate. Collapsing a browser window—or viewing the site on mobile—makes the menu do some wacky things because it's so wide. And when viewed in a mobile browser, the buttons cascade way down the screen and eat a lot of space. So I was thinking of ways to minimize buttons.

ok, so for this we should solve with a hamburger menu because this is just rank, and the hamburger menu is a common mobile UI component. 

> The issue with moving the top-level link to the Open Organization Definition is that so many things already link to it at theopenorganization.org/definition. 

Ok, so let's NOT change "definition" as a top level, leave that like it is. Because we don't want stuff breaking all over the place. What if we remix that page to point to the Maturity Model AND the OLD at the TOP and have a little intro paragraph? 

"Below you will find the Open Organization Definition, the seminal resource of the Open Organization Project. It is around this definition that the global community united and became active in helping others become more open. They have since developed:

A Maturity Model for Open Organizations (link)
The Open Leadership Definition (link)

> From a usability perspective, I'd prefer not to rely too heavily on dropdown menus because I always have trouble with sites that implement these when I'm using a mobile device. "Hovering" isn't really a thing with a touch interface.

+1 No submenus!!

**Comment by semioticrobotic** [comment]
> ok, so for this we should solve with a hamburger menu because this is just rank, and the hamburger menu is a common mobile UI component.

Agree completely. I just ... don't know how to do this (yet). Do you? I'm sure we can learn (or find someone who can help). In the meantime, what if we edited the CSS to format the buttons a little differently for smaller screen sizes? I know it makes the tap targets smaller, but surely a _little_ smaller than they currently are wouldn't hurt that much?

> Ok, so let's NOT change "definition" as a top level, leave that like it is. Because we don't want stuff breaking all over the place. What if we remix that page to point to the Maturity Model AND the OLD at the TOP and have a little intro paragraph?

Now this I like. If I have a moment, I can mock something up. Maybe I can still salvage this branch. Maybe not. Or maybe you can in a way I cannot. :smile: 

> +1 No submenus!!

:100:

**Comment by semioticrobotic** [comment]
For example, as a stopgap, it could look like this.

Screenshot from 2021-08-05 08-01-09

**Comment by LauraHilliger** [comment]
just did a quick search but haven't had time to tinker on this. Storing this here for future reference :) Jekyll codex has a toggle menu: https://jekyllcodex.org/without-plugin/toggle-menu/

**Pull request closed without merging**
