### PR TITLE
Had tinker time (aka The Tinkertime Diaries)

### PR DESCRIPTION
**Pull request by LauraHilliger**
I just installed a full jekyll template minima and tinkered with markdowns to get us started

### CODE REVIEW

**Comment by semioticrobotic** [comment]
Thank you, @LauraHilliger!

I would like to review this a little more deeply, though in the interim I believe a few components of the proposed site here should be up for community discussion. Just a few things I see, for example:

- It looks like the proposed site includes some kind of "blog" functionality. Is that something we want? Something we're willing to maintain? And how do we do it?
- It looks like this site hooks into a discussion-facilitation instrument. Is this something we want to facilitate on the site? Something we have the capacity to maintain?
- It looks like this site uses Google Analytics to track usage and metrics. Are we all okay with that? And how do we set it up if so? Who has access, etc.?

I am certainly not an expert in web design, of course, so maybe I am misunderstanding the code I'm reviewing (it would not surprise me!). Corrections welcome. :smile: 

In the meantime, if there's some even lighter-weight/lower-overhead template we can deploy, just to get some basics up and running, perhaps we could do that as we discuss the larger "infrastructural" issues.

**Comment by semioticrobotic** [comment]
It also looks like this template includes a full code of conduct document, but I'd be reluctant to make something like that "live" before the community reviews, updates, and ratifies it.

**Comment by semioticrobotic** [comment]
> In the meantime, if there's some even lighter-weight/lower-overhead template we can deploy, just to get some basics up and running, perhaps we could do that as we discuss the larger "infrastructural" issues.

Just for example, when I look at our GitHub Pages settings, I see this "Theme Chooser":

Screenshot from 2020-06-24 11-27-38

While perhaps none of the themes it offers are ideal, at least they seem to be more like a "baby step" on the road to a fuller-blown website like the one your PR proposes, and could serve us until we can spend the time discussing and building out specific functionality.

**Comment by LauraHilliger** [comment]
Ahh ;) Ok – so I saw that what was in this repo wasn't even a full Jekyll package, so I installed it thinking that we could start working on a repo with at least a base jekyll installed. I had tinker time, and idk when infra folks might have time, so I just sort of started. I thought maybe it's fun to start looking into the submodules thing, depending on availability of Red Hat folks. 

The prereq though seemed like at least that base install. I didn't even know that Github now has Jekyll functionality as, like, settings. We can toss this whole PR if someone else is already working! 

Also, we can force an index page of some sort, so that folks can't see what we're doing while we're doing it.

> * It looks like the proposed site includes some kind of "blog" functionality. Is that something we want? Something we're willing to maintain? And how do we do it?

I don't _think_ we want to use the blog functionality, but Jekyll is a static site blog engine, so that's just default functionality. On other sites I've built using jekyll, we've just not used posts :)

> * It looks like this site hooks into a discussion-facilitation instrument. Is this something we want to facilitate on the site? Something we have the capacity to maintain?

Heh? Whatcha talkin about on this one? Screenshot?

> * It looks like this site uses Google Analytics to track usage and metrics. Are we all okay with that? And how do we set it up if so? Who has access, etc.?
Also a default install with the Minima theme (which I choose only because that was in the original config file

ANNNNDDD the Code of Conduct is default installed with the theme as well, I didn't even notice it, but yes 100% agree that we need to work on that (we can remove it for now).

**Comment by semioticrobotic** [comment]
> Ok – so I saw that what was in this repo wasn't even a full Jekyll package, so I installed it thinking that we could start working on a repo with at least a base jekyll installed. 

Ah, yes! This explanation of what I'm seeing in the repo makes sense to me. Thanks for your patience and explaining it to me. @MarkusTiede had a few things set up here, and we retained them when we moved in so that the transition was a bit easier. (Markus has been away from his computer on leave for several weeks and I did not want to pester him too much about the site and its requirements.)

> I had tinker time, and idk when infra folks might have time, so I just sort of started. I thought maybe it's fun to start looking into the submodules thing, depending on availability of Red Hat folks. The prereq though seemed like at least that base install.

"I just sort of started" is a great attitude to have, and one that we can all benefit from, for sure. To be clear, we're not in some way required to route requests for this kind of work through the community infra team, so personally I'm glad you plowed ahead and ran this experiment so we could begin the learning process. Your "tinker time" is more rare than ever these days—and therefore incredibly valuable—and we are all lucky that you chose to funnel some of it into this project, from which we will all benefit immensely. Thank you. :pray: 

> Heh? Whatcha talkin about on this one? Screenshot?

I was seeing lots of references to "disqus" variables, etc., which I thought I remembered being some kind of cross-site commenting feature. I can look up additional details, though, to be sure.

> I didn't even know that Github now has Jekyll functionality as, like, settings. We can toss this whole PR if someone else is already working! Also, we can force an index page of some sort, so that folks can't see what we're doing while we're doing it.

I really like this idea, @LauraHilliger (if I understand the meaning of "force an index page" here). How about this: Why don't we explore the built-in functionality first, as that seems to give us a nice, low-barrier, "baby step" springboard to begin spinning up something manageable. In my opinion, we're looking for something that allows us to begin architecting according to your excellent [site map](https://www.mindmeister.com/1522721021?t=KsYDyrHW6k) as quickly and easily as possible. That map indicates that the ``open-organization.github.io`` repository would house a home page that then linked to pages housed in *other* repositories (for example, in the ``Books & Resources`` section, a link to the *Open Organization Leaders Manual*, which points to a page that's housed in the repository in ``open-org-leaders-manual``. Then the team working on the *Leaders Manual* can maintain both the manual itself and the info/download page for the manual. Hopefully that makes sense? Pushback welcome.

This way, we've tried some simple things on our own, and if we need help from the community infra superheros, we can go to them with more targeted questions or a request that's a little more specific than "can haz site pls?"—what do you think?

**Comment by semioticrobotic** [comment]
I've had more time to [review documentation](https://help.github.com/en/github/working-with-github-pages/about-custom-domains-and-github-pages) and I think what we'd ultimately like to do is not only possible but also the *default behavior* for GitHub Pages. It never works out that easily!

So I'm [seeing this](https://help.github.com/en/github/working-with-github-pages/about-custom-domains-and-github-pages):

> After you configure a custom domain for a user or organization site, the custom domain will replace the `<user>.github.io` or `<organization>.github.io` portion of the URL for any project sites owned by the account that do not have a custom domain configured. For example, if the custom domain for your user site is `www.octocat.com`, and you have a project site with no custom domain configured that is published from a repository called `octo-project`, the GitHub Pages site for that repository will be available at `www.octocat.com/octo-project`.

To me, that implies that we can host our primary site at `theopenorganization.org` and allow each project to exist as its own independent page in the site architecture, like:

- `theopenorganization.org/open-org-definition`
- `theopenorganization.org/open-org-leaders-manual`

We could simply determine which of the standard-issue, "click-to-deploy' templates in the GitHub Pages settings we want to use for these, then configure a page accordingly in every repository. Or we could choose a third-party template and just ensure that we've standardized it across the board.

Getting closer!

**Comment by semioticrobotic** [comment]
Cool! I was able to push some revisions to your main branch, @LauraHilliger. I really just wanted to rehearse the process and continue teaching myself how this worked. I did switch the theme (it's not necessarily my favorite or my preference, just something a little simpler that I could more easily comprehend), but retained your basic file and directory/menu structure. We're not merged into the production branch yet, so we can't really see any of this online, but maybe there's a way to switch Pages "on" for this repository so we can use your branch as a staging area, then the main branch as a production environment when we're ready to go live post-sprint.

Sorry, hope this makes sense. Mind is still spinning a little. Thanks for the tutorial!

**Comment by LauraHilliger** [comment]
Heyyy - ok, so FWIW I'm not a pro. Disclaimer because I think @jonasrosland can maybe teach us both how we SHOULD be doing it. But since he's not here right now:

I can't write to this repo, so I can't fix conflicts in the main branch on the main repo. I put the site on pages in my repo, so we can see what's going on:

https://laurahilliger.github.io/open-organization.github.io/

**Comment by semioticrobotic** [comment]
> Heyyy - ok, so FWIW I'm not a pro. Disclaimer because I think @jonasrosland can maybe teach us both how we SHOULD be doing it. But since he's not here right now: I can't write to this repo, so I can't fix conflicts in the main branch on the main repo.

Well, you're way further along than I am, so that means I am looking up to you, expertise or not. :smile: 

Also FWIW, I too am unable to resolve the merge conflict we're seeing (tried a few things a few days ago), so I'm not entirely sure it's a permissions issue, but I will check that, too, just to be sure (thought you'd be able to write here). Either way, we're not in any rush to get a site "into production," so we can simply experiment in this branch, and then @jonasrosland can set us right when it's time. I fully expect to have all this self-taught knowledge wiped clean by his tutelage (look forward to it!).

In the meantime, though, I will continue to play when I have aforementioned tinker time.

> I put the site on pages in my repo, so we can see what's going on:
> 
> https://laurahilliger.github.io/open-organization.github.io/

Thank you so much. Super helpful for me. I look forward to continuing to poke around and learn.

**Comment by LauraHilliger** [comment]
@semioticrobotic I put the base pages in there and cleaned up a bit, also installed a gem based theme...Really, I was just trying to figure out how we need to structure things. Is deploying here (example):
https://openorg-bb2s.onrender.com/open-principles/

OBVIOUSLY loads to do to make this not suck, but :)

**Comment by semioticrobotic** [comment]
> OBVIOUSLY loads to do to make this not suck, but :)

Yes, but look at how awesome it already is! Nice work. I will continue to update content in the ``_pages`` directory.

**Comment by semioticrobotic** [comment]
Working on this was on my list for today, but you beat me to it. :smile: Looking forward to diving into your additions.

**Comment by semioticrobotic** [comment]
I had some, shall we say, "tinker time" this afternoon, so I continued the work up updating basic page content. It appears to be going well (I should hope so; it essentially amounts to updating markdown files).

My focus this week has been primarily on _content_, as I know _styling_ is still up for discussion and decision. I'd like to tentatively suggest that we:

1. Settle on a new template, one that we feel will be "the one" moving forward, and then
2. Deploy it "fresh," either in a cleaned-out repository or through some other method

At the moment, I get the impression that we're actually working with files jumbled together from two different templates, and it's creating some rendering issues (also some confusion on my end, as I work with the documentation for [Minimal Mistakes](https://github.com/mmistakes/minimal-mistakes) to determine what should be there and what's a relic of a prior iteration with an outdated template). I'd like to begin working on other parts of the site—page styling, color scheme standardization in line with the new brand, logo placement, links to feeds and social media, etc.—but I don't want to get too deeply into that work only to have the template change.

Either way, it looks like we can simply port everything in the ``_pages`` directory to a new home in a new site build, wherever and whenever we do that. In the meantime, I'll keep updating stuff in that folder.

**Comment by semioticrobotic** [comment]
I had more tinker time. It's not necessarily the direction we outlined in any of the work above (sorry), but it's a process I could get my head around and something I think can scale. [See what you think in the production repo](http://theopenorganization.org/). Feedback most definitely welcome.

**Pull request closed without merging**
